#!/usr/bin/env php
<?php

require __DIR__ . '/Source/Commands/Add.php';
require __DIR__ . '/Source/Commands/Initialize.php';

$command = getopt('', ['command::'])['command'] ?? 'help';

switch ($command) {
    case 'initialize':
       \Saeghe\Saeghe\Commands\Initialize\run();
       break;
    case 'add':
        \Saeghe\Saeghe\Commands\Add\run();
        break;
    default:
        // TODO: Add help
        break;
}
