#!/usr/bin/env php
<?php

require __DIR__ . '/Source/Commands/Add.php';
require __DIR__ . '/Source/Commands/Build.php';
require __DIR__ . '/Source/Commands/Initialize.php';

$project = getopt('', ['project::'])['project'] ?? '';
$config = getopt('', ['config::'])['config'] ?? 'build.json';

$projectRoot = strlen($project) ? $_SERVER['PWD'] . '/' . $project . '/' : $_SERVER['PWD'] . '/';
$configPath = $projectRoot . $config;

$setting = [];
if (file_exists($configPath)) {
    $setting = json_decode(json: file_get_contents($configPath), associative: true, flags: JSON_THROW_ON_ERROR);
}

$lockPath = str_replace('.json', '.lock', $configPath);
$lockSetting = [];
if (file_exists($lockPath)) {
    $lockSetting = json_decode(json: file_get_contents($lockPath), associative: true, flags: JSON_THROW_ON_ERROR);
}

$command = getopt('', ['command::'])['command'] ?? 'help';

switch ($command) {
    case 'initialize':
       \Saeghe\Saeghe\Commands\Initialize\run();
       break;
    case 'add':
        \Saeghe\Saeghe\Commands\Add\run();
        break;
    case 'build':
        \Saeghe\Saeghe\Commands\Build\run();
        break;
    default:
        // TODO: Add help
        break;
}
