#!/usr/bin/env php
<?php

require __DIR__ . DIRECTORY_SEPARATOR . 'Source' . DIRECTORY_SEPARATOR . 'Str.php';
require __DIR__ . DIRECTORY_SEPARATOR . 'Source' . DIRECTORY_SEPARATOR . 'Path.php';

use Saeghe\Saeghe\Path;

require_once Path::fromString(__DIR__ . '/Packages/saeghe/cli/Source/IO/Read.php')->toString();
require_once Path::fromString(__DIR__ . '/Packages/saeghe/cli/Source/IO/Write.php')->toString();
require_once Path::fromString(__DIR__ . '/Packages/saeghe/test-runner/Source/Assertions/File.php')->toString();

require_once Path::fromString(__DIR__ . '/Packages/saeghe/test-runner/run')->toString();


