#!/usr/bin/env php
<?php

require \realpath(__DIR__ . '/Import.php');
require_once \realpath(__DIR__ . '/Packages/saeghe/test-runner/Source/Assertions/Boolean.php');
require_once \realpath(__DIR__ . '/Packages/saeghe/test-runner/Source/Assertions/Str.php');
require_once \realpath(__DIR__ . '/Packages/saeghe/test-runner/Source/Assertions/File.php');
require_once \realpath(__DIR__ . '/Packages/saeghe/test-runner/run');

function root(): string
{
    return getcwd() . DIRECTORY_SEPARATOR;
}
